/* Orabyher app bundle — generated by build-bundle.py */
/* Source files remain editable; re-run: python3 build-bundle.py */


/* ==== data.js ==== */
window.STORE = {
  siteUrl: "https://shop.orabyher.workers.dev",
  whatsapp: "919686516174",
  categories: [
    {
      id: "necklace-haram",
      name: "Necklace & Haram",
      image: "category_icons-17700551431279.webp"
    },
    {
      id: "bangles-bracelets",
      name: "Bangles & Bracelets",
      image: "category_icons-17700553911027.webp"
    },
    {
      id: "earrings",
      name: "Earrings",
      image: "category_icons-17700554902769.webp"
    },
    {
      id: "invisible-chains",
      name: "Invisible Chains",
      image: "category_icons-invisible-chains.jpg"
    }
  ],
  products: [
    {
      id: "palakka-necklace-279",
      name: "Palakka Temple Necklace Set",
      price: 279,
      mrp: 279,
      categoryId: "necklace-haram",
      rating: 4.8,
      reviews: 0,
      image: "product-palakka-necklace-279.jpg",
      images: [
        "product-palakka-necklace-279.jpg"
      ],
      description: "Traditional Palakka necklace set with antique gold finish, emerald-green centre stone, ruby accents, and matching earrings — a classic temple jewellery look for festive occasions.",
      highlights: [
        "Necklace with matching earrings",
        "Palakka green centre stone",
        "Antique gold temple finish",
        "Ruby red border accents",
        "Festive & bridal friendly"
      ],
      specs: {
        Material: "Alloy with antique gold plating",
        Occasion: "Festival / Wedding",
        Colour: "Antique Gold / Green / Red",
        Set: "Necklace + Earrings",
        "Care Instructions": "Wipe with soft dry cloth"
      },
      sections: [
        "trending",
        "bestsellers",
        "popular",
        "new"
      ],
      inStock: true
    },
    {
      id: "palakka-necklace-259",
      name: "Palakka Green Pendant Necklace Set",
      price: 259,
      mrp: 259,
      categoryId: "necklace-haram",
      rating: 4.7,
      reviews: 0,
      image: "product-palakka-necklace-259.jpg",
      images: [
        "product-palakka-necklace-259.jpg"
      ],
      description: "Elegant Palakka pendant necklace with sleek gold chain, green shield motif, and matching stud earrings — light traditional charm for daily festive wear.",
      highlights: [
        "Matching earring set",
        "Green Palakka pendant",
        "Sleek gold chain",
        "Lightweight comfort",
        "Everyday festive wear"
      ],
      specs: {
        Material: "Alloy with gold plating",
        Occasion: "Party / Festival",
        Colour: "Gold / Green",
        Set: "Necklace + Earrings",
        "Care Instructions": "Keep away from water & perfume"
      },
      sections: [
        "trending",
        "popular",
        "new"
      ],
      inStock: true
    },
    {
      id: "simple-chain-199",
      name: "Simple Mango Motif Chain",
      price: 199,
      mrp: 199,
      categoryId: "necklace-haram",
      rating: 4.6,
      reviews: 0,
      image: "product-simple-chain-199.jpg",
      images: [
        "product-simple-chain-199.jpg"
      ],
      description: "Minimal gold-tone chain with a refined mango motif pendant and emerald green inlay — simple, elegant heritage for everyday styling.",
      highlights: [
        "Minimal mango motif",
        "Delicate gold chain",
        "Green stone accent",
        "Everyday elegance",
        "Easy to layer"
      ],
      specs: {
        Material: "Alloy with gold plating",
        Occasion: "Daily / Casual festive",
        Colour: "Gold / Green",
        "Care Instructions": "Store in dry pouch"
      },
      sections: [
        "new",
        "popular",
        "trending"
      ],
      inStock: true
    },
    {
      id: "long-haram-399",
      name: "Long Green Temple Haram",
      price: 399,
      mrp: 399,
      categoryId: "necklace-haram",
      rating: 4.9,
      reviews: 0,
      image: "product-long-haram-399.jpg",
      images: [
        "product-long-haram-399.jpg"
      ],
      description: "Statement long haram with emerald green stones, ruby accents, and antique gold floral motifs — crafted for grand festive and bridal looks.",
      highlights: [
        "Long haram silhouette",
        "Green & ruby stone work",
        "Temple floral motifs",
        "Bridal statement piece",
        "Antique gold finish"
      ],
      specs: {
        Material: "Alloy with antique gold plating",
        Occasion: "Bridal / Ceremony",
        Colour: "Antique Gold / Green / Red",
        "Care Instructions": "Wipe gently after use"
      },
      sections: [
        "bestsellers",
        "trending",
        "new",
        "popular"
      ],
      inStock: true
    },
    {
      id: "white-pearl-jhumka-380",
      name: "White Pearl Jhumka",
      price: 380,
      mrp: 380,
      categoryId: "earrings",
      rating: 4.8,
      reviews: 0,
      inStock: true,
      image: "product-white-pearl-jhumka-380.jpg",
      images: [
        "product-white-pearl-jhumka-380.jpg",
        "product-white-pearl-jhumka-380-2.jpg",
        "product-white-pearl-jhumka-380-3.jpg"
      ],
      description: "Antique-finish temple jhumkas with Lakshmi motif tops, ornate filigree bells, and a fringe of white pearls — classic festive earrings with rich heritage charm.",
      highlights: [
        "Lakshmi motif temple tops",
        "Ornate filigree jhumka bells",
        "White pearl fringe drops",
        "Antique gold finish",
        "Festive & bridal friendly"
      ],
      specs: {
        Material: "Alloy with antique gold plating / Pearls",
        Occasion: "Festival / Wedding",
        Colour: "Antique Gold / White Pearl",
        Set: "Pair of earrings",
        "Care Instructions": "Wipe with soft dry cloth; keep pearls dry"
      },
      sections: [
        "new",
        "bestsellers",
        "popular",
        "trending"
      ]
    },
    {
      id: "temple-jhumkas-380",
      name: "Temple Jhumkas",
      price: 380,
      mrp: 380,
      categoryId: "earrings",
      rating: 4.8,
      reviews: 0,
      inStock: true,
      image: "product-temple-jhumkas-380.jpg",
      images: [
        "product-temple-jhumkas-380.jpg",
        "product-temple-jhumkas-380-2.jpg",
        "product-temple-jhumkas-380-3.jpg"
      ],
      description: "Antique-finish temple jhumkas with Lakshmi motif studs and arched bells, red and green stone accents, and a pearl fringe — rich festive earrings for traditional looks.",
      highlights: [
        "Lakshmi temple motif studs",
        "Arched jhumka with deity detail",
        "Red & green stone accents",
        "White pearl fringe",
        "Antique gold festive finish"
      ],
      specs: {
        Material: "Alloy with antique gold plating / Stones / Pearls",
        Occasion: "Festival / Wedding",
        Colour: "Antique Gold / Red / Green / Pearl",
        Set: "Pair of earrings",
        "Care Instructions": "Wipe with soft dry cloth; keep pearls dry"
      },
      sections: [
        "new",
        "bestsellers",
        "popular",
        "trending"
      ]
    },
    {
      id: "green-stud-earring-199",
      name: "Green Stud Earing",
      price: 199,
      mrp: 199,
      categoryId: "earrings",
      rating: 4.6,
      reviews: 0,
      inStock: true,
      image: "product-green-stud-earring-199.jpg",
      images: [
        "product-green-stud-earring-199.jpg",
        "product-green-stud-earring-199-2.jpg"
      ],
      description: "Antique-finish temple earrings with Lakshmi motif medallions, emerald green bead accents, layered deity detail, and a classic jhumka drop with beaded fringe.",
      highlights: [
        "Lakshmi motif temple medallions",
        "Emerald green bead accents",
        "Layered deity cluster detail",
        "Classic jhumka drop",
        "Antique gold festive finish"
      ],
      specs: {
        Material: "Alloy with antique gold plating / Green beads",
        Occasion: "Festival / Party",
        Colour: "Antique Gold / Green",
        Set: "Pair of earrings",
        "Care Instructions": "Wipe with soft dry cloth"
      },
      sections: [
        "new",
        "popular",
        "trending"
      ]
    },
    {
      id: "blue-hanging-earring-220",
      name: "Blue Hanging Thread Earrings",
      price: 220,
      mrp: 220,
      categoryId: "earrings",
      rating: 4.6,
      reviews: 0,
      inStock: true,
      image: "product-blue-hanging-earring-220.jpg",
      images: [
        "product-blue-hanging-earring-220.jpg"
      ],
      description: "Antique silver-tone square plaque earrings with navy blue silk thread drops and ghungroo accents — a soft ethnic hang for festive and daily wear.",
      highlights: [
        "Navy blue silk thread drops",
        "Antique silver-tone finish",
        "Embossed square plaque",
        "Ghungroo bead accents",
        "Lightweight ethnic hang"
      ],
      specs: {
        Material: "Alloy / Silk thread",
        Occasion: "Daily / Festival",
        Colour: "Silver / Navy Blue",
        "Care Instructions": "Keep thread dry; store separately"
      },
      sections: [
        "new",
        "popular",
        "trending"
      ]
    },
    {
      id: "blue-statement-earrings-269",
      name: "Blue Statement Fabric Earrings",
      price: 269,
      mrp: 269,
      categoryId: "earrings",
      rating: 4.7,
      reviews: 0,
      inStock: true,
      image: "product-blue-statement-earrings-269.jpg",
      images: [
        "product-blue-statement-earrings-269.jpg"
      ],
      description: "Indigo batik-print diamond fabric earrings with silver flower centre and ghungroo fringe — a bold handmade statement for festive looks.",
      highlights: [
        "Indigo batik fabric",
        "Layered diamond shape",
        "Silver flower centre",
        "Ghungroo fringe detail",
        "Handmade statement pair"
      ],
      specs: {
        Material: "Fabric / Alloy accents",
        Occasion: "Festival / Party",
        Colour: "Indigo / Silver",
        "Care Instructions": "Keep dry; avoid crushing fringe"
      },
      sections: [
        "bestsellers",
        "new",
        "popular",
        "trending"
      ]
    },
    {
      id: "lotus-invisible-chain-219",
      name: "Lotus Invisible Chain Set",
      price: 219,
      mrp: 219,
      categoryId: "invisible-chains",
      rating: 4.7,
      reviews: 0,
      inStock: true,
      image: "product-lotus-invisible-chain-219.jpg",
      images: [
        "product-lotus-invisible-chain-219.jpg"
      ],
      description: "Delicate invisible chain set with gold-tone lotus pendants and matching lotus stud earrings — a soft, barely-there festive look.",
      highlights: [
        "Invisible chain with lotus pendants",
        "Matching lotus stud earrings",
        "Gold-tone finish",
        "Lightweight everyday wear",
        "Adjustable clasp chain"
      ],
      specs: {
        Material: "Invisible cord with alloy accents",
        Occasion: "Daily / Festival",
        Colour: "Gold / Transparent",
        "Care Instructions": "Keep dry; wipe gently"
      },
      sections: [
        "new",
        "trending",
        "popular",
        "bestsellers"
      ]
    },
    {
      id: "navaratna-bangles-359",
      name: "Navaratna Multicolor Bangle Set",
      price: 359,
      mrp: 359,
      categoryId: "bangles-bracelets",
      rating: 4.7,
      reviews: 0,
      inStock: true,
      image: "product-navaratna-bangles-359.jpg",
      images: [
        "product-navaratna-bangles-359.jpg"
      ],
      description: "Set of four gold-tone Navaratna-inspired bangles with multicolor stone accents — vibrant festive wear for traditional outfits.",
      highlights: [
        "Set of 4 bangles",
        "Multicolor stone accents",
        "Gold-tone finish",
        "Festive traditional look",
        "Comfortable everyday festive wear"
      ],
      specs: {
        Material: "Alloy with gold plating",
        Occasion: "Festival / Party",
        Colour: "Gold / Multicolor",
        "Care Instructions": "Wipe with soft dry cloth"
      },
      sections: [
        "trending",
        "new",
        "popular",
        "bestsellers"
      ]
    },
    {
      id: "pearl-adjustable-bangle-220",
      name: "Pearl Adjustable Cuff Bangle",
      price: 220,
      mrp: 220,
      categoryId: "bangles-bracelets",
      rating: 4.6,
      reviews: 0,
      inStock: false,
      image: "product-pearl-adjustable-bangle-220.jpg",
      images: [
        "product-pearl-adjustable-bangle-220.jpg"
      ],
      description: "Elegant open adjustable cuff bangle with pearl drops and pink stone accents — a soft traditional finish for everyday styling.",
      highlights: [
        "Adjustable open cuff",
        "Pearl drop accents",
        "Pink stone detailing",
        "Lightweight comfort",
        "Currently out of stock"
      ],
      specs: {
        Material: "Alloy with gold plating",
        Occasion: "Daily / Party",
        Colour: "Gold / Pearl / Pink",
        "Care Instructions": "Keep pearls dry"
      },
      sections: [
        "new",
        "popular"
      ]
    },
    {
      id: "palaka-bangle-389",
      name: "Palaka Green & Pink Bangle Pair",
      price: 389,
      mrp: 389,
      categoryId: "bangles-bracelets",
      rating: 4.8,
      reviews: 0,
      inStock: true,
      image: "product-palaka-bangle-389.jpg",
      images: [
        "product-palaka-bangle-389.jpg"
      ],
      description: "Ornate Palaka-style bangle pair with emerald green stones and pink kemp accents in rich gold-tone floral work.",
      highlights: [
        "Pair of bangles",
        "Green Palaka stones",
        "Pink kemp accents",
        "Traditional floral work",
        "Bridal & festive favourite"
      ],
      specs: {
        Material: "Alloy with gold plating",
        Occasion: "Wedding / Festival",
        Colour: "Gold / Green / Pink",
        "Care Instructions": "Store separately to avoid scratches"
      },
      sections: [
        "bestsellers",
        "trending",
        "new",
        "popular"
      ]
    }
  ]
};


window.getProductById = function (id) {
  return STORE.products.find(function (p) {
    return p.id === id;
  });
};

window.getCategoryById = function (id) {
  return STORE.categories.find(function (c) {
    return c.id === id;
  });
};

window.getProductsByCategory = function (categoryId) {
  return STORE.products.filter(function (p) {
    return p.categoryId === categoryId;
  });
};

window.getProductsBySection = function (section) {
  return STORE.products.filter(function (p) {
    return p.sections && p.sections.indexOf(section) !== -1;
  });
};

window.formatINR = function (amount) {
  return (
    "₹" +
    Number(amount).toLocaleString("en-IN", {
      maximumFractionDigits: 0,
    })
  );
};

window.isProductOutOfStock = function (product) {
  if (!product) return false;
  if (product.inStock === false) return true;
  var name = String(product.name || "").toLowerCase();
  var id = String(product.id || "").toLowerCase();
  return (
    name.indexOf("stock out") !== -1 ||
    name.indexOf("sold out") !== -1 ||
    id.indexOf("sold_out") !== -1 ||
    id.indexOf("stock_out") !== -1
  );
};

/* ==== cart.js ==== */
(function () {
  var CART_KEY = "multimart_cart_v1";
  var WHATSAPP = "919686516174";

  function readCart() {
    try {
      return JSON.parse(localStorage.getItem(CART_KEY) || "[]");
    } catch (e) {
      return [];
    }
  }

  function writeCart(items) {
    localStorage.setItem(CART_KEY, JSON.stringify(items));
    updateCartBadge();
    window.dispatchEvent(new CustomEvent("cart:updated"));
  }

  function findProduct(id) {
    return window.getProductById ? getProductById(id) : null;
  }

  function getCart() {
    return readCart();
  }

  function getCartCount() {
    return readCart().reduce(function (sum, item) {
      return sum + (item.qty || 0);
    }, 0);
  }

  function addToCart(productId, qty) {
    qty = qty || 1;
    var product = findProduct(productId);
    if (!product) return;
    if (
      window.isProductOutOfStock
        ? isProductOutOfStock(product)
        : product.inStock === false
    ) {
      showToast("This product is out of stock");
      return;
    }
    var items = readCart();
    var existing = items.find(function (i) {
      return i.id === productId;
    });
    if (existing) {
      existing.qty += qty;
    } else {
      items.push({
        id: product.id,
        name: product.name,
        price: product.price,
        image: product.image,
        qty: qty,
      });
    }
    writeCart(items);
    showToast(product.name + " added to cart");
  }

  function setQty(productId, qty) {
    var items = readCart();
    items = items
      .map(function (i) {
        if (i.id === productId) i.qty = Math.max(1, qty);
        return i;
      })
      .filter(function (i) {
        return i.qty > 0;
      });
    writeCart(items);
  }

  function removeFromCart(productId) {
    writeCart(
      readCart().filter(function (i) {
        return i.id !== productId;
      })
    );
  }

  function clearCart() {
    writeCart([]);
  }

  function cartTotal() {
    return readCart().reduce(function (sum, i) {
      return sum + i.price * i.qty;
    }, 0);
  }

  function productWhatsAppMessage(product, qty) {
    qty = qty || 1;
    var pageUrl =
      window.location.origin +
      window.location.pathname.replace(/[^/]*$/, "") +
      "product.html?id=" +
      product.id;
    return [
      "Hello! I am interested in this product:",
      "",
      "*" + product.name + "*",
      "Price: *" + formatINR(product.price) + "*",
      "Qty: " + qty,
      "Link: " + pageUrl,
    ].join("\n");
  }

  function openWhatsAppForProduct(productId, qty) {
    var product = findProduct(productId);
    if (!product) return;
    var text = encodeURIComponent(productWhatsAppMessage(product, qty));
    window.open("https://wa.me/" + WHATSAPP + "?text=" + text, "_blank");
  }

  function notifyWhatsAppMessage(product) {
    var pageUrl =
      window.location.origin +
      window.location.pathname.replace(/[^/]*$/, "") +
      "product.html?id=" +
      product.id;
    return [
      "Hello! Please *NOTIFY* me when this product is back in stock:",
      "",
      "*" + product.name + "*",
      "Price: *" + formatINR(product.price) + "*",
      "Status: Out of stock",
      "Link: " + pageUrl,
    ].join("\n");
  }

  function openNotifyForProduct(productId) {
    var product = findProduct(productId);
    if (!product) return;
    var text = encodeURIComponent(notifyWhatsAppMessage(product));
    window.open("https://wa.me/" + WHATSAPP + "?text=" + text, "_blank");
  }

  function openWhatsAppForCart() {
    var items = readCart();
    if (!items.length) {
      showToast("Cart is empty");
      return;
    }
    var lines = ["Hello! I would like to order the following items:", ""];
    items.forEach(function (item, idx) {
      lines.push(
        idx +
          1 +
          ". " +
          item.name +
          " x " +
          item.qty +
          " = " +
          formatINR(item.price * item.qty)
      );
    });
    lines.push("");
    lines.push("Total: " + formatINR(cartTotal()));
    lines.push("");
    lines.push("Please share payment & delivery details.");
    var text = encodeURIComponent(lines.join("\n"));
    window.open("https://wa.me/" + WHATSAPP + "?text=" + text, "_blank");
  }

  function updateCartBadge() {
    var count = getCartCount();
    document.querySelectorAll("[data-cart-count]").forEach(function (el) {
      el.textContent = String(count);
      el.classList.toggle("hidden", count === 0);
      el.classList.toggle("inline-flex", count > 0);
    });
  }

  function showToast(message) {
    var existing = document.getElementById("store-toast");
    if (existing) existing.remove();
    var toast = document.createElement("div");
    toast.id = "store-toast";
    toast.className = "store-toast";
    toast.textContent = message;
    document.body.appendChild(toast);
    requestAnimationFrame(function () {
      toast.classList.add("show");
    });
    setTimeout(function () {
      toast.classList.remove("show");
      setTimeout(function () {
        toast.remove();
      }, 250);
    }, 2200);
  }

  function bindGlobalActions() {
    document.addEventListener("click", function (e) {
      var addBtn = e.target.closest("[data-add-cart]");
      if (addBtn) {
        e.preventDefault();
        e.stopPropagation();
        addToCart(addBtn.getAttribute("data-add-cart"), 1);
        return;
      }
      var waBtn = e.target.closest("[data-whatsapp]");
      if (waBtn) {
        e.preventDefault();
        e.stopPropagation();
        openWhatsAppForProduct(waBtn.getAttribute("data-whatsapp"), 1);
        return;
      }
      var notifyBtn = e.target.closest("[data-notify]");
      if (notifyBtn) {
        e.preventDefault();
        e.stopPropagation();
        openNotifyForProduct(notifyBtn.getAttribute("data-notify"));
        return;
      }
    });
    updateCartBadge();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", bindGlobalActions);
  } else {
    bindGlobalActions();
  }

  window.Cart = {
    getCart: getCart,
    getCartCount: getCartCount,
    addToCart: addToCart,
    setQty: setQty,
    removeFromCart: removeFromCart,
    clearCart: clearCart,
    cartTotal: cartTotal,
    openWhatsAppForProduct: openWhatsAppForProduct,
    openNotifyForProduct: openNotifyForProduct,
    openWhatsAppForCart: openWhatsAppForCart,
    updateCartBadge: updateCartBadge,
    showToast: showToast,
    WHATSAPP: WHATSAPP,
  };
})();

/* ==== menu.js ==== */
(function () {
  var LINKS = [
    { href: "index.html", label: "Home", icon: "home" },
    { href: "shop.html", label: "Shop" },
    { href: "customers.html", label: "Our Customers" },
    { href: "contact.html", label: "Contact" },
    { href: "cart.html", label: "Cart" },
  ];

  var IG_URL = "https://www.instagram.com/ora_by_her/";

  function currentPage() {
    var path = (window.location.pathname || "").split("/").pop() || "index.html";
    return path.toLowerCase();
  }

  function openMenu() {
    document.documentElement.classList.add("nav-open");
    var btn = document.getElementById("nav-burger");
    var drawer = document.getElementById("nav-drawer");
    if (btn) btn.setAttribute("aria-expanded", "true");
    if (drawer) drawer.setAttribute("aria-hidden", "false");
  }

  function closeMenu() {
    document.documentElement.classList.remove("nav-open");
    var btn = document.getElementById("nav-burger");
    var drawer = document.getElementById("nav-drawer");
    if (btn) btn.setAttribute("aria-expanded", "false");
    if (drawer) drawer.setAttribute("aria-hidden", "true");
  }

  function toggleMenu() {
    if (document.documentElement.classList.contains("nav-open")) closeMenu();
    else openMenu();
  }

  function initMobileMenu() {
    if (document.getElementById("nav-drawer")) return;

    var header = document.querySelector("header");
    if (!header) return;

    var desktopNav = header.querySelector("nav");
    if (desktopNav) desktopNav.classList.add("desktop-nav");

    var cartLink =
      header.querySelector('a[aria-label="Cart"]') ||
      header.querySelector('a[href="cart.html"]');

    var burger = document.createElement("button");
    burger.type = "button";
    burger.id = "nav-burger";
    burger.className = "nav-burger icon-btn";
    burger.setAttribute("aria-label", "Open menu");
    burger.setAttribute("aria-expanded", "false");
    burger.setAttribute("aria-controls", "nav-drawer");
    burger.innerHTML =
      '<span class="nav-burger-lines" aria-hidden="true">' +
      "<span></span><span></span><span></span>" +
      "</span>";

    if (cartLink && cartLink.parentNode) {
      cartLink.parentNode.insertBefore(burger, cartLink);
    } else {
      header.appendChild(burger);
    }

    var page = currentPage();
    var homeIcon =
      '<svg class="nav-home-icon" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M3 10.5L12 3l9 7.5V20a1 1 0 01-1 1h-5v-6H9v6H4a1 1 0 01-1-1v-9.5z"/></svg>';
    var linksHtml = LINKS.map(function (link) {
      var active =
        page === link.href.toLowerCase() ||
        (page === "" && link.href === "index.html");
      var label =
        link.icon === "home"
          ? homeIcon + "<span>" + link.label + "</span>"
          : link.label;
      return (
        '<a href="' +
        link.href +
        '" class="nav-drawer-link' +
        (active ? " is-active" : "") +
        (link.icon === "home" ? " nav-drawer-link-home" : "") +
        '">' +
        label +
        "</a>"
      );
    }).join("");

    var backdrop = document.createElement("div");
    backdrop.id = "nav-backdrop";
    backdrop.className = "nav-backdrop";
    backdrop.setAttribute("aria-hidden", "true");

    var drawer = document.createElement("aside");
    drawer.id = "nav-drawer";
    drawer.className = "nav-drawer";
    drawer.setAttribute("aria-hidden", "true");
    drawer.setAttribute("role", "dialog");
    drawer.setAttribute("aria-label", "Menu");
    drawer.innerHTML =
      '<div class="nav-drawer-head">' +
      '<a href="index.html" class="nav-drawer-brand">' +
      '<img src="logo.png" alt="Orabyher" />' +
      "</a>" +
      '<button type="button" id="nav-drawer-close" class="nav-drawer-close" aria-label="Close menu">' +
      '<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.8">' +
      '<path stroke-linecap="round" d="M6 6l12 12M18 6L6 18"/>' +
      "</svg>" +
      "</button>" +
      "</div>" +
      '<nav class="nav-drawer-nav">' +
      linksHtml +
      "</nav>";

    document.body.appendChild(backdrop);
    document.body.appendChild(drawer);

    burger.addEventListener("click", function (e) {
      e.preventDefault();
      toggleMenu();
    });
    backdrop.addEventListener("click", closeMenu);
    document
      .getElementById("nav-drawer-close")
      .addEventListener("click", closeMenu);
    drawer.querySelectorAll("a").forEach(function (a) {
      a.addEventListener("click", closeMenu);
    });
    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape") closeMenu();
    });
  }

  function initInstagramFab() {
    if (document.getElementById("ig-fab")) return;
    var fab = document.createElement("a");
    fab.id = "ig-fab";
    fab.className = "ig-fab";
    fab.href = IG_URL;
    fab.target = "_blank";
    fab.rel = "noopener noreferrer";
    fab.setAttribute("aria-label", "Instagram @ora_by_her");
    fab.title = "Instagram";
    fab.innerHTML =
      '<svg viewBox="0 0 24 24" aria-hidden="true" fill="currentColor">' +
      '<path d="M7.5 2h9A5.5 5.5 0 0122 7.5v9A5.5 5.5 0 0116.5 22h-9A5.5 5.5 0 012 16.5v-9A5.5 5.5 0 017.5 2zm0 2A3.5 3.5 0 004 7.5v9A3.5 3.5 0 007.5 20h9a3.5 3.5 0 003.5-3.5v-9A3.5 3.5 0 0016.5 4h-9zm9.25 1.75a1.25 1.25 0 110 2.5 1.25 1.25 0 010-2.5zM12 7a5 5 0 110 10 5 5 0 010-10zm0 2a3 3 0 100 6 3 3 0 000-6z"/>' +
      "</svg>";
    document.body.appendChild(fab);
  }

  function init() {
    initMobileMenu();
    initInstagramFab();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();

/* ==== share.js ==== */
(function () {
  function siteBase() {
    if (window.STORE && STORE.siteUrl) {
      return String(STORE.siteUrl).replace(/\/$/, "") + "/";
    }
    var path = window.location.pathname;
    var dir = path.endsWith("/")
      ? path
      : path.replace(/[^/]*$/, "");
    return window.location.origin + dir;
  }

  function absoluteUrl(path) {
    if (!path) return siteBase();
    if (/^https?:\/\//i.test(path)) return path;
    return siteBase() + path.replace(/^\//, "");
  }

  function productUrl(productId) {
    return absoluteUrl("product.html?id=" + encodeURIComponent(productId));
  }

  function setMeta(attr, key, value) {
    if (!value) return;
    var selector =
      attr === "property"
        ? 'meta[property="' + key + '"]'
        : 'meta[name="' + key + '"]';
    var el = document.querySelector(selector);
    if (!el) {
      el = document.createElement("meta");
      el.setAttribute(attr, key);
      document.head.appendChild(el);
    }
    el.setAttribute("content", value);
  }

  function applyDefaultOg() {
    var title =
      document.querySelector('meta[property="og:title"]') &&
      document.querySelector('meta[property="og:title"]').getAttribute("content");
    if (!title) title = document.title || "Orabyher";

    var descEl = document.querySelector('meta[name="description"]');
    var desc = descEl
      ? descEl.getAttribute("content")
      : "Orabyher — heritage jewellery crafted with timeless care.";

    var image = absoluteUrl("og-image.jpg");
    var url = window.location.href.split("#")[0];

    setMeta("property", "og:type", "website");
    setMeta("property", "og:site_name", "Orabyher");
    setMeta("property", "og:title", title);
    setMeta("property", "og:description", desc);
    setMeta("property", "og:image", image);
    setMeta("property", "og:image:width", "800");
    setMeta("property", "og:image:height", "800");
    setMeta("property", "og:url", url);
    setMeta("name", "twitter:card", "summary_large_image");
    setMeta("name", "twitter:title", title);
    setMeta("name", "twitter:description", desc);
    setMeta("name", "twitter:image", image);

    // Upgrade relative og:image if already present
    document
      .querySelectorAll(
        'meta[property="og:image"], meta[name="twitter:image"]'
      )
      .forEach(function (el) {
        var c = el.getAttribute("content") || "";
        if (c && !/^https?:\/\//i.test(c)) {
          el.setAttribute("content", absoluteUrl(c));
        }
      });
  }

  function setProductOg(product) {
    if (!product) return;
    var title = product.name + " | Orabyher";
    var desc =
      product.description ||
      product.name + " — " + formatINR(product.price) + " | Orabyher";
    var image = absoluteUrl(product.image || "logo.png");
    var url = productUrl(product.id);

    document.title = title;
    setMeta("name", "description", desc);
    setMeta("property", "og:type", "product");
    setMeta("property", "og:site_name", "Orabyher");
    setMeta("property", "og:title", title);
    setMeta("property", "og:description", desc);
    setMeta("property", "og:image", image);
    setMeta("property", "og:url", url);
    setMeta("name", "twitter:card", "summary_large_image");
    setMeta("name", "twitter:title", title);
    setMeta("name", "twitter:description", desc);
    setMeta("name", "twitter:image", image);
  }

  function canNativeShare() {
    return (
      typeof navigator !== "undefined" &&
      typeof navigator.share === "function" &&
      (/Mobi|Android|iPhone|iPad|iPod/i.test(navigator.userAgent) ||
        (navigator.maxTouchPoints && navigator.maxTouchPoints > 1))
    );
  }

  function copyText(text) {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      return navigator.clipboard.writeText(text);
    }
    return new Promise(function (resolve, reject) {
      var input = document.createElement("textarea");
      input.value = text;
      input.setAttribute("readonly", "");
      input.style.position = "fixed";
      input.style.left = "-9999px";
      document.body.appendChild(input);
      input.select();
      try {
        document.execCommand("copy");
        resolve();
      } catch (err) {
        reject(err);
      } finally {
        document.body.removeChild(input);
      }
    });
  }

  function shareProduct(productId) {
    var product = window.getProductById ? getProductById(productId) : null;
    var url = product ? productUrl(product.id) : window.location.href;
    var title = product ? product.name + " | Orabyher" : document.title;
    var text = product
      ? product.name + " — " + formatINR(product.price)
      : title;

    if (canNativeShare()) {
      navigator
        .share({ title: title, text: text, url: url })
        .catch(function () {
          /* user cancelled */
        });
      return;
    }

    copyText(url)
      .then(function () {
        if (window.Cart && Cart.showToast) Cart.showToast("Link copied");
        else alert("Link copied");
      })
      .catch(function () {
        if (window.Cart && Cart.showToast) Cart.showToast("Could not copy link");
        else prompt("Copy this link:", url);
      });
  }

  function shareCurrentPage() {
    var params = new URLSearchParams(window.location.search);
    var id = params.get("id");
    if (id) {
      shareProduct(id);
      return;
    }
    var url = window.location.href.split("#")[0];
    var title = document.title;
    if (canNativeShare()) {
      navigator.share({ title: title, url: url }).catch(function () {});
      return;
    }
    copyText(url).then(function () {
      if (window.Cart && Cart.showToast) Cart.showToast("Link copied");
    });
  }

  function bindShareClicks() {
    document.addEventListener("click", function (e) {
      var btn = e.target.closest("[data-share]");
      if (!btn) return;
      e.preventDefault();
      e.stopPropagation();
      var id = btn.getAttribute("data-share");
      if (id) shareProduct(id);
      else shareCurrentPage();
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", function () {
      applyDefaultOg();
      bindShareClicks();
    });
  } else {
    applyDefaultOg();
    bindShareClicks();
  }

  window.Share = {
    shareProduct: shareProduct,
    shareCurrentPage: shareCurrentPage,
    setProductOg: setProductOg,
    productUrl: productUrl,
    absoluteUrl: absoluteUrl,
  };
})();

/* ==== ui.js ==== */
(function () {
  function productCard(product) {
    var oos = window.isProductOutOfStock
      ? isProductOutOfStock(product)
      : product.inStock === false;
    var actionBtn = oos
      ? '<button type="button" data-notify="' +
        product.id +
        '" class="notify-icon-btn" aria-label="Notify me" title="Notify me">' +
        notifySvg() +
        "</button>"
      : '<button type="button" data-whatsapp="' +
        product.id +
        '" class="wa-icon-btn-sm" aria-label="WhatsApp">' +
        whatsappSvg() +
        "</button>";
    var overlayAction = oos
      ? '<button type="button" data-notify="' +
        product.id +
        '" class="notify-icon-btn" aria-label="Notify me" title="Notify me">' +
        notifySvg() +
        "</button>"
      : '<button type="button" data-whatsapp="' +
        product.id +
        '" class="wa-icon-btn" aria-label="WhatsApp" title="WhatsApp">' +
        whatsappSvg() +
        "</button>";
    var cartBtn = oos
      ? '<span class="oos-pill">Out of stock</span>'
      : '<button type="button" data-add-cart="' +
        product.id +
        '" class="w-10 h-10 bg-slate-100 rounded-full flex items-center justify-center text-slate-700 hover:bg-primary hover:text-white transition-all" aria-label="Add to cart">' +
        cartSvg() +
        "</button>";

    return (
      '<div class="group block h-full">' +
      '<div class="relative bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300 h-full border border-slate-100 flex flex-col">' +
      '<a href="product.html?id=' +
      product.id +
      '" class="relative aspect-square overflow-hidden bg-slate-50 block">' +
      '<img src="' +
      product.image +
      '" alt="' +
      product.name +
      '" loading="lazy" decoding="async" class="w-full h-full object-cover object-center transition-transform duration-500 group-hover:scale-110' +
      (oos ? " opacity-80" : "") +
      '" />' +
      (oos
        ? '<span class="absolute left-3 top-3 bg-stone-800 text-white text-[10px] font-semibold px-2 py-1 rounded uppercase tracking-wider">Sold out</span>'
        : "") +
      '<div class="absolute right-3 top-3 flex flex-col gap-2 sm:opacity-0 sm:group-hover:opacity-100 sm:translate-x-4 sm:group-hover:translate-x-0 transition-all duration-300">' +
      '<button type="button" data-share="' +
      product.id +
      '" class="share-icon-btn" aria-label="Share" title="Share">' +
      shareSvg() +
      "</button>" +
      overlayAction +
      "</div>" +
      "</a>" +
      '<div class="p-4 flex-grow flex flex-col">' +
      '<a href="product.html?id=' +
      product.id +
      '">' +
      '<h3 class="text-slate-800 font-semibold text-sm mb-1 leading-snug line-clamp-2 group-hover:text-primary transition-colors">' +
      product.name +
      "</h3>" +
      "</a>" +
      '<div class="mt-auto pt-3 flex items-center justify-between gap-2">' +
      '<div class="flex flex-col">' +
      '<span class="text-lg font-bold text-slate-900">' +
      formatINR(product.price) +
      "</span>" +
      "</div>" +
      '<div class="flex items-center gap-2">' +
      '<button type="button" data-share="' +
      product.id +
      '" class="share-icon-btn" aria-label="Share" title="Share">' +
      shareSvg() +
      "</button>" +
      actionBtn +
      cartBtn +
      "</div>" +
      "</div>" +
      "</div>" +
      "</div>" +
      "</div>"
    );
  }

  function whatsappSvg(cls) {
    cls = cls || "w-4 h-4";
    return (
      '<svg viewBox="0 0 24 24" class="' +
      cls +
      '" fill="currentColor" aria-hidden="true">' +
      '<path d="M20.52 3.48A11.78 11.78 0 0012.04 0C5.5 0 .2 5.3.2 11.82c0 2.08.55 4.11 1.6 5.9L0 24l6.45-1.69a11.8 11.8 0 005.58 1.42h.01c6.54 0 11.84-5.3 11.84-11.82 0-3.16-1.23-6.13-3.36-8.43zM12.04 21.2h-.01a9.8 9.8 0 01-5-1.37l-.36-.21-3.83 1 1.02-3.73-.24-.38a9.8 9.8 0 01-1.5-5.23c0-5.42 4.42-9.83 9.86-9.83a9.78 9.78 0 016.97 16.8 9.8 9.8 0 01-6.91 2.95zm5.4-7.36c-.3-.15-1.75-.86-2.02-.96-.27-.1-.47-.15-.67.15-.2.3-.77.96-.94 1.16-.17.2-.35.22-.64.07-.3-.15-1.25-.46-2.38-1.47-.88-.78-1.47-1.74-1.64-2.03-.17-.3-.02-.46.13-.6.13-.13.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.02-.52-.07-.15-.67-1.61-.92-2.2-.24-.58-.49-.5-.67-.5h-.57c-.2 0-.52.07-.8.37-.27.3-1.05 1.02-1.05 2.49s1.07 2.89 1.22 3.09c.15.2 2.11 3.22 5.11 4.51.71.31 1.27.49 1.7.63.72.23 1.37.2 1.89.12.58-.09 1.75-.72 2-1.41.25-.7.25-1.29.17-1.41-.07-.12-.27-.2-.57-.35z"/>' +
      "</svg>"
    );
  }

  function notifySvg(cls) {
    cls = cls || "w-4 h-4";
    return (
      '<svg class="' +
      cls +
      '" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">' +
      '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M15 17h5l-1.4-1.4A2 2 0 0118 14.2V11a6 6 0 10-12 0v3.2c0 .5-.2 1-.6 1.4L4 17h5m6 0a3 3 0 11-6 0"/>' +
      "</svg>"
    );
  }

  function shareSvg(cls) {
    cls = cls || "w-4 h-4";
    return (
      '<svg class="' +
      cls +
      '" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">' +
      '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M4 12v7a1 1 0 001 1h14a1 1 0 001-1v-7M16 6l-4-4-4 4M12 2v13"/>' +
      "</svg>"
    );
  }

  function cartSvg(cls) {
    cls = cls || "w-5 h-5";
    return (
      '<svg class="' +
      cls +
      '" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">' +
      '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"/>' +
      "</svg>"
    );
  }

  function renderGrid(selector, products) {
    var el = document.querySelector(selector);
    if (!el) return;
    if (!products.length) {
      el.innerHTML =
        '<p class="col-span-full text-center text-stone-500 py-10">No products found.</p>';
      return;
    }
    el.innerHTML = products.map(productCard).join("");
  }

  function renderCategoryGrid(selector) {
    var el = document.querySelector(selector);
    if (!el || !window.STORE) return;
    el.innerHTML = STORE.categories
      .map(function (cat) {
        return (
          '<a href="category.html?id=' +
          cat.id +
          '" class="group relative h-64 rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition-all">' +
          '<div class="absolute inset-0 bg-black/20 group-hover:bg-black/40 transition-colors z-10"></div>' +
          '<img src="' +
          cat.image +
          '" alt="' +
          cat.name +
          '" loading="lazy" decoding="async" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" />' +
          '<div class="absolute bottom-0 left-0 p-6 z-20">' +
          '<h3 class="text-white text-xl font-bold mb-1 translate-y-2 group-hover:translate-y-0 transition-transform">' +
          cat.name +
          "</h3>" +
          '<span class="text-white/80 text-sm opacity-0 group-hover:opacity-100 transition-opacity">Explore</span>' +
          "</div></a>"
        );
      })
      .join("");
  }

  window.UI = {
    productCard: productCard,
    renderGrid: renderGrid,
    renderCategoryGrid: renderCategoryGrid,
    whatsappSvg: whatsappSvg,
    notifySvg: notifySvg,
    shareSvg: shareSvg,
    cartSvg: cartSvg,
  };
})();

/* ==== loader.js ==== */
(function () {
  var LOADER_MIN_MS = 1200;

  function ensureLoader() {
    var existing = document.getElementById("page-loader");
    if (existing) return existing;

    var loader = document.createElement("div");
    loader.id = "page-loader";
    loader.className = "page-loader";
    loader.setAttribute("aria-hidden", "true");
    loader.innerHTML =
      '<div class="page-loader-inner">' +
      '<img src="logo.png" alt="Multimart" class="page-loader-logo" />' +
      '<div class="page-loader-ring"></div>' +
      '<p class="page-loader-text">Loading</p>' +
      "</div>";
    document.body.appendChild(loader);
    return loader;
  }

  function hideLoader() {
    var loader = document.getElementById("page-loader");
    if (!loader) return;
    loader.classList.add("is-done");
    setTimeout(function () {
      if (loader.parentNode) loader.parentNode.removeChild(loader);
      document.documentElement.classList.remove("is-loading");
    }, 500);
  }

  document.documentElement.classList.add("is-loading");
  ensureLoader();

  var started = Date.now();
  function finish() {
    var wait = Math.max(0, LOADER_MIN_MS - (Date.now() - started));
    setTimeout(hideLoader, wait);
  }

  if (document.readyState === "complete") {
    finish();
  } else {
    window.addEventListener("load", finish);
  }
})();

/* ==== customers-data.js ==== */
window.CUSTOMERS = [
  {
    "image": "customer-01.jpg",
    "caption": ""
  },
  {
    "image": "customer-02.jpg",
    "caption": ""
  },
  {
    "image": "customer-03.jpg",
    "caption": ""
  },
  {
    "image": "customer-04.jpg",
    "caption": ""
  },
  {
    "image": "customer-05.jpg",
    "caption": ""
  },
  {
    "image": "customer-06.jpg",
    "caption": ""
  },
  {
    "image": "customer-07.jpg",
    "caption": ""
  },
  {
    "image": "customer-08.jpg",
    "caption": ""
  },
  {
    "image": "customer-09.jpg",
    "caption": ""
  },
  {
    "image": "customer-10.jpg",
    "caption": ""
  },
  {
    "image": "customer-11.jpg",
    "caption": ""
  },
  {
    "image": "customer-12.jpg",
    "caption": ""
  },
  {
    "image": "customer-13.jpg",
    "caption": ""
  },
  {
    "image": "customer-14.jpg",
    "caption": ""
  },
  {
    "image": "customer-15.jpg",
    "caption": ""
  },
  {
    "image": "customer-16.jpg",
    "caption": ""
  },
  {
    "image": "customer-17.jpg",
    "caption": ""
  }
];

/* ==== instagram-data.js ==== */
window.INSTAGRAM = {
  profile: "ora_by_her",
  profileUrl: "https://www.instagram.com/ora_by_her/",
  // Add more Instagram post/reel URLs below to list them on the Instagram page
  posts: [
    {
      url: "https://www.instagram.com/p/DbXPhwoqiBb/",
      title: "Simple, elegant and beautiful",
      type: "post",
    },
  ],
};

/* ==== main.js (index.html) ==== */
(function () {
  var __p = (location.pathname.split('/').pop() || 'index.html').toLowerCase();
  if (!__p || __p === '/') __p = 'index.html';
  if (["index.html"].indexOf(__p) === -1) return;
const slides = [
  {
    title: "White Pearl Jhumka",
    image: "banner_images-white-pearl-jhumka.webp",
    href: "product.html?id=white-pearl-jhumka-380",
  },
  {
    title: "Temple Jhumkas",
    image: "banner_images-temple-jhumkas.webp",
    href: "product.html?id=temple-jhumkas-380",
  },
  {
    title: "10% Off For Nagas Collections",
    image: "banner_images-17700529852896.webp",
    href: "shop.html",
  },
  {
    title: "10% Off For Nagas Collections",
    image: "banner_images-17700532806776.webp",
    href: "shop.html",
  },
];

const titleEl = document.getElementById("hero-title");
const heroCta = document.querySelector(".hero-section a.px-10");
const slidesEl = document.getElementById("hero-slides");
const slidesMobileEl = document.getElementById("hero-slides-mobile");

function slideHtml(s, i, imgClass) {
  // Only the first slide loads immediately; others hydrate on show()
  var imgAttrs =
    i === 0
      ? 'src="' + s.image + '" fetchpriority="high"'
      : 'data-src="' + s.image + '" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"';
  return (
    '<div class="hero-slide' +
    (i === 0 ? " active" : "") +
    '"><img ' +
    imgAttrs +
    ' alt="' +
    s.title +
    '" class="' +
    imgClass +
    '" decoding="async" /></div>'
  );
}

function hydrateSlideImages(slideEl) {
  if (!slideEl) return;
  var img = slideEl.querySelector("img[data-src]");
  if (!img) return;
  img.src = img.getAttribute("data-src");
  img.removeAttribute("data-src");
}

if (slidesEl) {
  slidesEl.innerHTML = slides
    .map(function (s, i) {
      return slideHtml(s, i, "hero-slide-img-desktop");
    })
    .join("");
}

if (slidesMobileEl) {
  slidesMobileEl.innerHTML = slides
    .map(function (s, i) {
      return slideHtml(s, i, "hero-slide-img-mobile");
    })
    .join("");
}

function splitTitle(title) {
  var words = title.split(" ");
  if (words.length <= 3) return { first: words.join(" "), second: "" };
  var mid = Math.ceil(words.length / 2);
  return {
    first: words.slice(0, mid).join(" "),
    second: words.slice(mid).join(" "),
  };
}

var current = 0;

function show(i) {
  current = (i + slides.length) % slides.length;
  document.querySelectorAll(".hero-slide").forEach(function (el) {
    el.classList.remove("active");
  });
  if (slidesEl && slidesEl.children[current]) {
    hydrateSlideImages(slidesEl.children[current]);
    slidesEl.children[current].classList.add("active");
  }
  if (slidesMobileEl && slidesMobileEl.children[current]) {
    hydrateSlideImages(slidesMobileEl.children[current]);
    slidesMobileEl.children[current].classList.add("active");
  }
  var t = splitTitle(slides[current].title);
  if (titleEl) {
    titleEl.innerHTML =
      t.first +
      (t.second
        ? '<span class="block mt-2 text-white/90">' + t.second + "</span>"
        : "");
  }
  if (heroCta) {
    heroCta.setAttribute("href", slides[current].href || "shop.html");
  }
}

show(0);

var nextBtn = document.getElementById("hero-next");
var prevBtn = document.getElementById("hero-prev");
if (nextBtn) {
  nextBtn.onclick = function () {
    show(current + 1);
  };
}
if (prevBtn) {
  prevBtn.onclick = function () {
    show(current - 1);
  };
}
setInterval(function () {
  show(current + 1);
}, 4000);

var header = document.getElementById("site-header");

window.addEventListener("scroll", function () {
  if (!header) return;
  var scrolled = window.scrollY > 50;
  header.classList.toggle("absolute", !scrolled);
  header.classList.toggle("fixed", scrolled);
  header.classList.toggle("is-scrolled", scrolled);
});

UI.renderCategoryGrid("#category-grid");
UI.renderGrid("#trending-grid", getProductsBySection("trending").slice(0, 4));
UI.renderGrid("#bestsellers-grid", getProductsBySection("bestsellers").slice(0, 4));
UI.renderGrid("#new-grid", getProductsBySection("new").slice(0, 4));
UI.renderGrid("#popular-grid", getProductsBySection("popular").slice(0, 8));

})();

/* ==== shop.js (shop.html) ==== */
(function () {
  var __p = (location.pathname.split('/').pop() || 'index.html').toLowerCase();
  if (!__p || __p === '/') __p = 'index.html';
  if (["shop.html"].indexOf(__p) === -1) return;
(function () {
  var filterId = "all";

  function sortProducts(list, mode) {
    var items = list.slice();
    if (mode === "price-asc") {
      items.sort(function (a, b) {
        return a.price - b.price;
      });
    } else if (mode === "price-desc") {
      items.sort(function (a, b) {
        return b.price - a.price;
      });
    } else if (mode === "rating") {
      items.sort(function (a, b) {
        return b.rating - a.rating;
      });
    }
    return items;
  }

  function renderPills() {
    var el = document.getElementById("shop-pills");
    var pills = [{ id: "all", name: "All Products" }].concat(STORE.categories);
    el.innerHTML = pills
      .map(function (c) {
        var active = c.id === filterId;
        return (
          '<button type="button" data-filter="' +
          c.id +
          '" class="px-4 py-2 rounded-full text-xs uppercase tracking-wider border transition-all ' +
          (active
            ? "bg-primary text-white border-primary"
            : "bg-white text-slate-600 border-slate-200 hover:border-primary hover:text-primary") +
          '">' +
          c.name +
          "</button>"
        );
      })
      .join("");
  }

  function paint() {
    var products =
      filterId === "all" ? STORE.products.slice() : getProductsByCategory(filterId);
    var sorted = sortProducts(products, document.getElementById("shop-sort").value);
    document.getElementById("shop-count").textContent =
      sorted.length +
      " product" +
      (sorted.length === 1 ? "" : "s") +
      " · Prices in INR";
    UI.renderGrid("#shop-grid", sorted);
  }

  document.addEventListener("DOMContentLoaded", function () {
    renderPills();
    paint();

    document.getElementById("shop-pills").addEventListener("click", function (e) {
      var btn = e.target.closest("[data-filter]");
      if (!btn) return;
      filterId = btn.getAttribute("data-filter");
      renderPills();
      paint();
    });

    document.getElementById("shop-sort").onchange = paint;
  });
})();

})();

/* ==== product.js (product.html) ==== */
(function () {
  var __p = (location.pathname.split('/').pop() || 'index.html').toLowerCase();
  if (!__p || __p === '/') __p = 'index.html';
  if (["product.html"].indexOf(__p) === -1) return;
(function () {
  function getQueryId() {
    var params = new URLSearchParams(window.location.search);
    return params.get("id");
  }

  function render() {
    var id = getQueryId();
    var product = getProductById(id);
    var root = document.getElementById("product-root");

    if (!product) {
      root.innerHTML =
        '<div class="p-10 text-center"><p class="text-stone-500 mb-4">Product not found.</p><a href="index.html" class="text-primary underline">Back to home</a></div>';
      return;
    }

    document.title = product.name + " | Orabyher";
    if (window.Share && Share.setProductOg) Share.setProductOg(product);
    var category = getCategoryById(product.categoryId);
    var images = product.images && product.images.length ? product.images : [product.image];
    var oos = window.isProductOutOfStock
      ? isProductOutOfStock(product)
      : product.inStock === false;
    var primaryAction = oos
      ? '<button type="button" id="btn-notify" class="fk-btn fk-btn-notify fk-btn-icon">' +
        UI.notifySvg("w-5 h-5") +
        "<span>Notify</span></button>"
      : '<button type="button" id="btn-whatsapp" class="fk-btn fk-btn-wa fk-btn-icon">' +
        UI.whatsappSvg("w-5 h-5") +
        "<span>WhatsApp</span></button>";
    var cartAction = oos
      ? '<button type="button" id="btn-add-cart" class="fk-btn fk-btn-cart fk-btn-icon fk-btn-disabled" disabled aria-disabled="true">' +
        UI.cartSvg("w-5 h-5") +
        "<span>Out of Stock</span></button>"
      : '<button type="button" id="btn-add-cart" class="fk-btn fk-btn-cart fk-btn-icon">' +
        UI.cartSvg("w-5 h-5") +
        "<span>Add to Cart</span></button>";

    root.innerHTML =
      '<div class="grid grid-cols-1 lg:grid-cols-12 gap-0">' +
      '<div class="lg:col-span-5 p-4 md:p-6 border-b lg:border-b-0 lg:border-r border-slate-100">' +
      '<div class="flex gap-3">' +
      '<div class="hidden sm:flex flex-col gap-2 w-16 shrink-0" id="thumb-list"></div>' +
      '<div class="flex-1">' +
      '<div class="zoom-stage">' +
      '<div class="zoom-wrap" id="zoom-wrap">' +
      '<img id="main-image" src="' +
      images[0] +
      '" alt="' +
      product.name +
      '" class="zoom-img" />' +
      '<div class="zoom-lens" id="zoom-lens"></div>' +
      "</div>" +
      '<div class="zoom-result" id="zoom-result"></div>' +
      "</div>" +
      '<div class="mt-4 grid grid-cols-1 sm:grid-cols-3 gap-3">' +
      cartAction +
      primaryAction +
      '<button type="button" id="btn-share" class="fk-btn fk-btn-share fk-btn-icon" data-share="' +
      product.id +
      '">' +
      UI.shareSvg("w-5 h-5") +
      "<span>Share</span></button>" +
      "</div>" +
      "</div>" +
      "</div>" +
      "</div>" +
      '<div class="lg:col-span-7 p-5 md:p-8">' +
      '<nav class="text-xs text-stone-400 mb-3 flex flex-wrap gap-1">' +
      '<a href="index.html" class="hover:text-primary">Home</a><span>/</span>' +
      (category
        ? '<a href="category.html?id=' +
          category.id +
          '" class="hover:text-primary">' +
          category.name +
          "</a><span>/</span>"
        : "") +
      '<span class="text-stone-600">' +
      product.name +
      "</span>" +
      "</nav>" +
      '<div class="flex items-start justify-between gap-3 mb-4">' +
      '<h1 class="text-2xl md:text-3xl font-medium text-slate-900 leading-snug">' +
      product.name +
      "</h1>" +
      '<button type="button" data-share="' +
      product.id +
      '" class="share-text-btn shrink-0" aria-label="Share product">' +
      UI.shareSvg() +
      "<span>Share</span></button>" +
      "</div>" +
      '<div class="flex items-end gap-3 mb-2">' +
      '<span class="text-3xl font-bold text-slate-900">' +
      formatINR(product.price) +
      "</span>" +
      (oos
        ? '<span class="oos-status-badge">Out of stock</span>'
        : "") +
      "</div>" +
      '<p class="text-xs text-stone-500 mb-6">Inclusive of all taxes · Prices in INR</p>' +
      (oos
        ? ""
        : '<div class="mb-6">' +
          '<label class="text-sm font-medium text-slate-700 mb-2 block">Quantity</label>' +
          '<div class="inline-flex items-center border border-slate-200 rounded-lg overflow-hidden">' +
          '<button type="button" id="qty-minus" class="px-3 py-2 hover:bg-slate-50">−</button>' +
          '<input id="qty-input" type="number" min="1" value="1" class="w-14 text-center border-x border-slate-200 py-2 outline-none" />' +
          '<button type="button" id="qty-plus" class="px-3 py-2 hover:bg-slate-50">+</button>' +
          "</div>" +
          "</div>") +
      '<div class="mb-8">' +
      '<h2 class="text-sm font-semibold uppercase tracking-wider text-primary mb-3">Highlights</h2>' +
      '<ul class="grid sm:grid-cols-2 gap-2 text-sm text-slate-700">' +
      product.highlights
        .map(function (h) {
          return (
            '<li class="flex gap-2"><span class="text-accent">•</span><span>' +
            h +
            "</span></li>"
          );
        })
        .join("") +
      "</ul>" +
      "</div>" +
      '<div class="mb-8">' +
      '<h2 class="text-sm font-semibold uppercase tracking-wider text-primary mb-3">Description</h2>' +
      '<p class="text-stone-600 leading-relaxed">' +
      product.description +
      "</p>" +
      "</div>" +
      '<div class="border border-slate-100 rounded-xl overflow-hidden">' +
      '<h2 class="text-sm font-semibold uppercase tracking-wider text-primary px-4 py-3 bg-cream border-b border-slate-100">Specifications</h2>' +
      '<table class="w-full text-sm">' +
      Object.keys(product.specs)
        .map(function (key) {
          return (
            '<tr class="border-b border-slate-50">' +
            '<td class="px-4 py-3 text-stone-500 w-1/3">' +
            key +
            "</td>" +
            '<td class="px-4 py-3 text-slate-800">' +
            product.specs[key] +
            "</td>" +
            "</tr>"
          );
        })
        .join("") +
      "</table>" +
      "</div>" +
      "</div>" +
      "</div>";

    var thumbList = document.getElementById("thumb-list");
    thumbList.innerHTML = images
      .map(function (src, i) {
        return (
          '<button type="button" class="thumb-btn' +
          (i === 0 ? " active" : "") +
          '" data-src="' +
          src +
          '"><img src="' +
          src +
          '" alt="" /></button>'
        );
      })
      .join("");

    setupGallery(images[0]);
    setupActions(product);

    var similar = getProductsByCategory(product.categoryId)
      .filter(function (p) {
        return p.id !== product.id;
      })
      .slice(0, 4);
    if (!similar.length) similar = getProductsBySection("popular").slice(0, 4);
    UI.renderGrid("#similar-grid", similar);
  }

  function setupGallery(initialSrc) {
    var mainImage = document.getElementById("main-image");
    var wrap = document.getElementById("zoom-wrap");
    var lens = document.getElementById("zoom-lens");
    var result = document.getElementById("zoom-result");

    function setImage(src) {
      mainImage.src = src;
      result.style.backgroundImage = "url('" + src + "')";
    }

    setImage(initialSrc);

    document.querySelectorAll(".thumb-btn").forEach(function (btn) {
      btn.addEventListener("click", function () {
        document.querySelectorAll(".thumb-btn").forEach(function (b) {
          b.classList.remove("active");
        });
        btn.classList.add("active");
        setImage(btn.getAttribute("data-src"));
      });
    });

    function moveLens(e) {
      var rect = wrap.getBoundingClientRect();
      var x = e.clientX - rect.left;
      var y = e.clientY - rect.top;
      var lensW = lens.offsetWidth / 2;
      var lensH = lens.offsetHeight / 2;

      if (x < lensW) x = lensW;
      if (x > rect.width - lensW) x = rect.width - lensW;
      if (y < lensH) y = lensH;
      if (y > rect.height - lensH) y = rect.height - lensH;

      lens.style.left = x - lensW + "px";
      lens.style.top = y - lensH + "px";

      var fx = (x / rect.width) * 100;
      var fy = (y / rect.height) * 100;
      result.style.backgroundPosition = fx + "% " + fy + "%";
    }

    wrap.addEventListener("mouseenter", function () {
      if (window.innerWidth < 1024) return;
      lens.classList.add("show");
      result.classList.add("show");
    });
    wrap.addEventListener("mouseleave", function () {
      lens.classList.remove("show");
      result.classList.remove("show");
    });
    wrap.addEventListener("mousemove", function (e) {
      if (window.innerWidth < 1024) return;
      moveLens(e);
    });
  }

  function setupActions(product) {
    var oos = window.isProductOutOfStock
      ? isProductOutOfStock(product)
      : product.inStock === false;
    var qtyInput = document.getElementById("qty-input");
    if (qtyInput) {
      document.getElementById("qty-minus").onclick = function () {
        qtyInput.value = Math.max(1, parseInt(qtyInput.value || "1", 10) - 1);
      };
      document.getElementById("qty-plus").onclick = function () {
        qtyInput.value = Math.max(1, parseInt(qtyInput.value || "1", 10) + 1);
      };
    }
    var addBtn = document.getElementById("btn-add-cart");
    if (addBtn && !oos) {
      addBtn.onclick = function () {
        Cart.addToCart(product.id, parseInt((qtyInput && qtyInput.value) || "1", 10));
      };
    }
    var waBtn = document.getElementById("btn-whatsapp");
    if (waBtn) {
      waBtn.onclick = function () {
        Cart.openWhatsAppForProduct(
          product.id,
          parseInt((qtyInput && qtyInput.value) || "1", 10)
        );
      };
    }
    var notifyBtn = document.getElementById("btn-notify");
    if (notifyBtn) {
      notifyBtn.onclick = function () {
        Cart.openNotifyForProduct(product.id);
      };
    }
  }

  document.addEventListener("DOMContentLoaded", render);
})();

})();

/* ==== category.js (category.html) ==== */
(function () {
  var __p = (location.pathname.split('/').pop() || 'index.html').toLowerCase();
  if (!__p || __p === '/') __p = 'index.html';
  if (["category.html"].indexOf(__p) === -1) return;
(function () {
  var currentId = null;

  function getQueryId() {
    return new URLSearchParams(window.location.search).get("id");
  }

  function renderPills() {
    var el = document.getElementById("cat-pills");
    el.innerHTML = STORE.categories
      .map(function (c) {
        var active = c.id === currentId;
        return (
          '<a href="category.html?id=' +
          c.id +
          '" class="px-4 py-2 rounded-full text-xs uppercase tracking-wider border transition-all ' +
          (active
            ? "bg-primary text-white border-primary"
            : "bg-white text-slate-600 border-slate-200 hover:border-primary hover:text-primary") +
          '">' +
          c.name +
          "</a>"
        );
      })
      .join("");
  }

  function sortProducts(list, mode) {
    var items = list.slice();
    if (mode === "price-asc") {
      items.sort(function (a, b) {
        return a.price - b.price;
      });
    } else if (mode === "price-desc") {
      items.sort(function (a, b) {
        return b.price - a.price;
      });
    } else if (mode === "rating") {
      items.sort(function (a, b) {
        return b.rating - a.rating;
      });
    }
    return items;
  }

  function render() {
    currentId = getQueryId() || STORE.categories[0].id;
    var category = getCategoryById(currentId);
    if (!category) {
      document.getElementById("cat-title").textContent = "Category not found";
      document.getElementById("category-grid").innerHTML =
        '<p class="col-span-full text-center text-stone-500 py-10">Invalid category.</p>';
      return;
    }

    document.title = category.name + " | Multimart";
    document.getElementById("cat-title").textContent = category.name;
    document.getElementById("cat-crumb").textContent = category.name;
    document.getElementById("cat-hero-img").src = category.image;
    document.getElementById("cat-hero-img").alt = category.name;

    renderPills();

    var products = getProductsByCategory(currentId);
    document.getElementById("cat-count").textContent =
      products.length + " product" + (products.length === 1 ? "" : "s") + " · Prices in INR";

    function paint() {
      var sorted = sortProducts(
        products,
        document.getElementById("sort-select").value
      );
      UI.renderGrid("#category-grid", sorted);
    }

    document.getElementById("sort-select").onchange = paint;
    paint();
  }

  document.addEventListener("DOMContentLoaded", render);
})();

})();

/* ==== cart-page.js (cart.html) ==== */
(function () {
  var __p = (location.pathname.split('/').pop() || 'index.html').toLowerCase();
  if (!__p || __p === '/') __p = 'index.html';
  if (["cart.html"].indexOf(__p) === -1) return;
(function () {
  function render() {
    var items = Cart.getCart();
    var root = document.getElementById("cart-items");
    document.getElementById("summary-count").textContent = String(Cart.getCartCount());
    document.getElementById("summary-total").textContent = formatINR(Cart.cartTotal());

    if (!items.length) {
      root.innerHTML =
        '<div class="bg-white rounded-2xl border border-slate-100 p-10 text-center">' +
        '<p class="text-stone-500 mb-4">Your cart is empty.</p>' +
        '<a href="shop.html" class="text-primary underline text-sm">Browse products</a>' +
        "</div>";
      return;
    }

    root.innerHTML = items
      .map(function (item) {
        return (
          '<div class="bg-white rounded-2xl border border-slate-100 p-4 flex gap-4 items-center">' +
          '<a href="product.html?id=' +
          item.id +
          '" class="w-24 h-24 rounded-xl overflow-hidden bg-slate-50 shrink-0">' +
          '<img src="' +
          item.image +
          '" alt="' +
          item.name +
          '" class="w-full h-full object-cover" />' +
          "</a>" +
          '<div class="flex-1 min-w-0">' +
          '<a href="product.html?id=' +
          item.id +
          '" class="font-semibold text-slate-800 hover:text-primary line-clamp-2">' +
          item.name +
          "</a>" +
          '<div class="text-lg font-bold mt-1">' +
          formatINR(item.price) +
          "</div>" +
          '<div class="flex items-center gap-3 mt-3">' +
          '<div class="inline-flex items-center border border-slate-200 rounded-lg overflow-hidden">' +
          '<button type="button" class="px-2 py-1 hover:bg-slate-50" data-qty-minus="' +
          item.id +
          '">−</button>' +
          '<span class="px-3 text-sm">' +
          item.qty +
          "</span>" +
          '<button type="button" class="px-2 py-1 hover:bg-slate-50" data-qty-plus="' +
          item.id +
          '">+</button>' +
          "</div>" +
          '<button type="button" class="text-xs text-stone-400 hover:text-red-600" data-remove="' +
          item.id +
          '">Remove</button>' +
          '<button type="button" class="wa-icon-btn-sm" data-whatsapp="' +
          item.id +
          '" aria-label="WhatsApp">' +
          UI.whatsappSvg() +
          "</button>" +
          "</div>" +
          "</div>" +
          '<div class="text-right font-semibold text-slate-900 shrink-0">' +
          formatINR(item.price * item.qty) +
          "</div>" +
          "</div>"
        );
      })
      .join("");
  }

  document.addEventListener("DOMContentLoaded", function () {
    render();

    document.getElementById("cart-items").addEventListener("click", function (e) {
      var minus = e.target.closest("[data-qty-minus]");
      var plus = e.target.closest("[data-qty-plus]");
      var remove = e.target.closest("[data-remove]");
      if (minus) {
        var id = minus.getAttribute("data-qty-minus");
        var item = Cart.getCart().find(function (i) {
          return i.id === id;
        });
        if (item) {
          if (item.qty <= 1) Cart.removeFromCart(id);
          else Cart.setQty(id, item.qty - 1);
        }
        render();
      }
      if (plus) {
        var pid = plus.getAttribute("data-qty-plus");
        var found = Cart.getCart().find(function (i) {
          return i.id === pid;
        });
        if (found) Cart.setQty(pid, found.qty + 1);
        render();
      }
      if (remove) {
        Cart.removeFromCart(remove.getAttribute("data-remove"));
        render();
      }
    });

    document.getElementById("btn-wa-bulk").onclick = function () {
      Cart.openWhatsAppForCart();
    };
    document.getElementById("btn-clear").onclick = function () {
      Cart.clearCart();
      render();
    };

    window.addEventListener("cart:updated", render);
  });
})();

})();

/* ==== customers.js (customers.html) ==== */
(function () {
  var __p = (location.pathname.split('/').pop() || 'index.html').toLowerCase();
  if (!__p || __p === '/') __p = 'index.html';
  if (["customers.html"].indexOf(__p) === -1) return;
(function () {
  function render() {
    var grid = document.getElementById("customers-grid");
    var empty = document.getElementById("customers-empty");
    if (!grid) return;

    var items = Array.isArray(window.CUSTOMERS) ? window.CUSTOMERS : [];
    if (!items.length) {
      grid.innerHTML = "";
      if (empty) empty.classList.remove("hidden");
      return;
    }

    if (empty) empty.classList.add("hidden");
    grid.innerHTML = items
      .map(function (item, i) {
        var caption = item.caption || "Our customer";
        return (
          '<button type="button" class="customer-card" data-index="' +
          i +
          '" aria-label="' +
          caption.replace(/"/g, "&quot;") +
          '">' +
          '<img src="' +
          item.image +
          '" alt="' +
          caption.replace(/"/g, "&quot;") +
          '" loading="lazy" />' +
          '<span class="customer-card-glow"></span>' +
          (item.caption
            ? '<span class="customer-card-caption">' + item.caption + "</span>"
            : "") +
          "</button>"
        );
      })
      .join("");

    bindLightbox(items);
  }

  function bindLightbox(items) {
    var lightbox = document.getElementById("customer-lightbox");
    var img = document.getElementById("customer-lightbox-img");
    var caption = document.getElementById("customer-lightbox-caption");
    var closeBtn = document.getElementById("customer-lightbox-close");
    var prevBtn = document.getElementById("customer-lightbox-prev");
    var nextBtn = document.getElementById("customer-lightbox-next");
    if (!lightbox || !img) return;

    var current = 0;

    function openAt(index) {
      current = (index + items.length) % items.length;
      var item = items[current];
      img.src = item.image;
      img.alt = item.caption || "Our customer";
      if (caption) caption.textContent = item.caption || "";
      lightbox.classList.add("is-open");
      lightbox.setAttribute("aria-hidden", "false");
      document.documentElement.classList.add("lightbox-open");
    }

    function close() {
      lightbox.classList.remove("is-open");
      lightbox.setAttribute("aria-hidden", "true");
      document.documentElement.classList.remove("lightbox-open");
    }

    document.querySelectorAll(".customer-card").forEach(function (card) {
      card.addEventListener("click", function () {
        openAt(parseInt(card.getAttribute("data-index"), 10) || 0);
      });
    });

    if (closeBtn) closeBtn.onclick = close;
    lightbox.addEventListener("click", function (e) {
      if (e.target === lightbox) close();
    });
    if (prevBtn) {
      prevBtn.onclick = function (e) {
        e.stopPropagation();
        openAt(current - 1);
      };
    }
    if (nextBtn) {
      nextBtn.onclick = function (e) {
        e.stopPropagation();
        openAt(current + 1);
      };
    }
    document.addEventListener("keydown", function (e) {
      if (!lightbox.classList.contains("is-open")) return;
      if (e.key === "Escape") close();
      if (e.key === "ArrowLeft") openAt(current - 1);
      if (e.key === "ArrowRight") openAt(current + 1);
    });
  }

  document.addEventListener("DOMContentLoaded", render);
})();

})();

/* ==== instagram.js (instagram.html) ==== */
(function () {
  var __p = (location.pathname.split('/').pop() || 'index.html').toLowerCase();
  if (!__p || __p === '/') __p = 'index.html';
  if (["instagram.html"].indexOf(__p) === -1) return;
(function () {
  function render() {
    var grid = document.getElementById("ig-grid");
    var profileLink = document.getElementById("ig-profile-link");
    var handleEl = document.getElementById("ig-handle");
    if (!window.INSTAGRAM || !grid) return;

    if (profileLink) profileLink.href = INSTAGRAM.profileUrl;
    if (handleEl) handleEl.textContent = "@" + INSTAGRAM.profile;

    var posts = INSTAGRAM.posts || [];
    if (!posts.length) {
      grid.innerHTML =
        '<p class="col-span-full text-center text-stone-500 py-10">No Instagram posts listed yet.</p>';
      return;
    }

    grid.innerHTML = posts
      .map(function (post, index) {
        var url = post.url.replace(/\/?$/, "/");
        return (
          '<article class="ig-card">' +
          '<div class="ig-card-head">' +
          '<span class="ig-card-label">' +
          (post.type === "reel" ? "Reel" : "Video / Post") +
          " " +
          (index + 1) +
          "</span>" +
          '<a href="' +
          url +
          '" target="_blank" rel="noopener" class="ig-card-open">Open on Instagram</a>' +
          "</div>" +
          (post.title
            ? '<h3 class="ig-card-title">' + post.title + "</h3>"
            : "") +
          '<div class="ig-embed-wrap">' +
          '<blockquote class="instagram-media" data-instgrm-permalink="' +
          url +
          '" data-instgrm-version="14" style="background:#FFF;border:0;border-radius:12px;margin:0 auto;max-width:540px;min-width:260px;width:100%;">' +
          '<a href="' +
          url +
          '" target="_blank" rel="noopener">View this post on Instagram</a>' +
          "</blockquote>" +
          "</div>" +
          "</article>"
        );
      })
      .join("");

    if (window.instgrm && window.instgrm.Embeds) {
      window.instgrm.Embeds.process();
    }
  }

  document.addEventListener("DOMContentLoaded", render);
})();

})();
