#!/usr/bin/env python3
"""Build app.js — one cached JS file for the whole site."""

from pathlib import Path

ROOT = Path(__file__).resolve().parent

CORE = [
    "data.js",
    "cart.js",
    "menu.js",
    "share.js",
    "ui.js",
    "loader.js",
    "customers-data.js",
    "instagram-data.js",
    "pwa.js",
]

# page filename → script
PAGES = [
    ("main.js", ("index.html",)),
    ("shop.js", ("shop.html",)),
    ("product.js", ("product.html",)),
    ("category.js", ("category.html",)),
    ("cart-page.js", ("cart.html",)),
    ("customers.js", ("customers.html",)),
    ("instagram.js", ("instagram.html",)),
]


def wrap_page(code: str, pages: tuple[str, ...]) -> str:
    names = ", ".join(f'"{p}"' for p in pages)
    # Cloudflare Workers often serves /product instead of /product.html
    return (
        "(function () {\n"
        "  var __p = (location.pathname.split('/').pop() || 'index.html').toLowerCase();\n"
        "  if (!__p || __p === '/') __p = 'index.html';\n"
        "  if (__p.indexOf('.') === -1) __p += '.html';\n"
        f"  if ([{names}].indexOf(__p) === -1) return;\n"
        f"{code}\n"
        "})();\n"
    )


def main() -> None:
    parts = [
        "/* Orabyher app bundle — generated by build-bundle.py */\n",
        "/* Source files remain editable; re-run: python3 build-bundle.py */\n\n",
    ]
    for name in CORE:
        parts.append(f"\n/* ==== {name} ==== */\n")
        parts.append((ROOT / name).read_text(encoding="utf-8"))
        if not parts[-1].endswith("\n"):
            parts.append("\n")

    for name, pages in PAGES:
        parts.append(f"\n/* ==== {name} ({', '.join(pages)}) ==== */\n")
        code = (ROOT / name).read_text(encoding="utf-8")
        parts.append(wrap_page(code, pages))

    out = ROOT / "app.js"
    out.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
