#!/usr/bin/env python3
"""Build site.css = local fonts + Tailwind utilities + theme styles."""

from pathlib import Path

ROOT = Path(__file__).resolve().parent

FONTS = """
/* Local fonts — same-origin, fewer third-party requests */
@font-face {
  font-family: "Inter";
  font-style: normal;
  font-weight: 300 700;
  font-display: swap;
  src: url("fonts/inter-latin.woff2") format("woff2");
}
@font-face {
  font-family: "Cormorant Garamond";
  font-style: normal;
  font-weight: 300 600;
  font-display: swap;
  src: url("fonts/cormorant-latin.woff2") format("woff2");
}
@font-face {
  font-family: "Cormorant Garamond";
  font-style: italic;
  font-weight: 300 600;
  font-display: swap;
  src: url("fonts/cormorant-italic-latin.woff2") format("woff2");
}
"""


def main() -> None:
    tw = (ROOT / "tailwind.gen.css").read_text(encoding="utf-8")
    theme = (ROOT / "style.css").read_text(encoding="utf-8")
    out = ROOT / "site.css"
    out.write_text(
        "/* Orabyher site.css — generated by build-css.py */\n"
        + FONTS
        + "\n/* ---- Tailwind ---- */\n"
        + tw
        + "\n/* ---- Theme ---- */\n"
        + theme,
        encoding="utf-8",
    )
    print(f"Wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
