#!/usr/bin/env python3
"""Build app.js and stamp content-hash cache-bust query on HTML assets."""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent

CORE = [
    "data.js",
    "cart.js",
    "menu.js",
    "share.js",
    "ui.js",
    "loader.js",
    "customers-data.js",
    "instagram-data.js",
    "pwa.js",
]

# page filename → script
PAGES = [
    ("main.js", ("index.html",)),
    ("shop.js", ("shop.html",)),
    ("product.js", ("product.html",)),
    ("category.js", ("category.html",)),
    ("cart-page.js", ("cart.html",)),
    ("customers.js", ("customers.html",)),
    ("instagram.js", ("instagram.html",)),
]


def wrap_page(code: str, pages: tuple[str, ...]) -> str:
    names = ", ".join(f'"{p}"' for p in pages)
    # Cloudflare Workers often serves /product instead of /product.html
    return (
        "(function () {\n"
        "  var __p = (location.pathname.split('/').pop() || 'index.html').toLowerCase();\n"
        "  if (!__p || __p === '/') __p = 'index.html';\n"
        "  if (__p.indexOf('.') === -1) __p += '.html';\n"
        f"  if ([{names}].indexOf(__p) === -1) return;\n"
        f"{code}\n"
        "})();\n"
    )


def short_hash(*paths: Path) -> str:
    h = hashlib.sha1()
    for path in paths:
        h.update(path.read_bytes())
    return h.hexdigest()[:10]


def stamp_asset_versions(version: str) -> None:
    css_href = f"site.css?v={version}"
    js_src = f"app.js?v={version}"
    for html in sorted(ROOT.glob("*.html")):
        text = html.read_text(encoding="utf-8")
        new = text
        new = re.sub(r'href="site\.css(?:\?v=[^"]*)?"', f'href="{css_href}"', new)
        new = re.sub(r'src="app\.js(?:\?v=[^"]*)?"', f'src="{js_src}"', new)
        if new != text:
            html.write_text(new, encoding="utf-8")
            print(f"Stamped {html.name} -> v={version}")


def main() -> None:
    parts = [
        "/* Orabyher app bundle — generated by build-bundle.py */\n",
        "/* Source files remain editable; re-run: python3 build-bundle.py */\n\n",
    ]
    for name in CORE:
        parts.append(f"\n/* ==== {name} ==== */\n")
        parts.append((ROOT / name).read_text(encoding="utf-8"))
        if not parts[-1].endswith("\n"):
            parts.append("\n")

    for name, pages in PAGES:
        parts.append(f"\n/* ==== {name} ({', '.join(pages)}) ==== */\n")
        code = (ROOT / name).read_text(encoding="utf-8")
        parts.append(wrap_page(code, pages))

    out = ROOT / "app.js"
    out.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {out} ({out.stat().st_size} bytes)")

    css = ROOT / "site.css"
    version = short_hash(out, css if css.exists() else out)
    stamp_asset_versions(version)
    print(f"Asset version {version}")


if __name__ == "__main__":
    main()
